version: "3"
services:
  grpc-executor:
    image: "mophos/r7platform-mophos/r7platform-grpc-executor"
    container_name: "grpc-executor"
    environment:
      - NODE_ENV=development
      - R7PLATFORM_GRPC_EXECUTOR_DB_HOST=127.0.0.1
      - R7PLATFORM_GRPC_EXECUTOR_DB_PORT=5433
      - R7PLATFORM_GRPC_EXECUTOR_DB_NAME=r7platform
      - R7PLATFORM_GRPC_EXECUTOR_DB_SCHEMA=rawdata
      - R7PLATFORM_GRPC_EXECUTOR_DB_USER=postgres
      - R7PLATFORM_GRPC_EXECUTOR_DB_PASSWORD=123456
      - R7PLATFORM_GRPC_EXECUTOR_DB_POOL_MIN=2
      - R7PLATFORM_GRPC_EXECUTOR_DB_POOL_MAX=100
      - R7PLATFORM_GRPC_EXECUTOR_SECRET_KEY=xeIjNUj8oF5KCitrAYxTAPWeZOjZZVHw
      - R7PLATFORM_GRPC_EXECUTOR_DB_DEBUG=Y

    ports:
      - 50051:50051

    restart: always
